### ISSUE TITLE
ex06_realtime_move is failing with Proficio

### ISSUE THREAD

**Issue by mhariharasudan** [BarrettTechnology/libbarrett#14]
Eigen error is thrown since the program manipulates the joint values of the variable jt_type which is > 3 and hence it fails for Proficio.

**Comment by amyblank** [comment]
I have a fix for this, but I think I don't have write access to the libbarrett repo.

**Comment by mhariharasudan** [comment]
You will be able to write to the repo now

**Comment by mhariharasudan** [comment]
This bug was fixed as part of #16
