### ISSUE TITLE
Any documentation or examples for the python bindings?

### ISSUE THREAD

**Issue by BenBlumer** [BarrettTechnology/libbarrett#17]
Is there any documentation or example programs available for the python bindings?  Are they equivalent to all the CPP libraries?

**Comment by bzenowich** [comment]
This file tests most of the Python interface:
https://github.com/BarrettTechnology/libbarrett/blob/devel/src/python_interface_test.py

And this example program uses Python to read the F/T sensor's accelerometer:
https://github.com/BarrettTechnology/libbarrett/blob/devel/sandbox/displayAccel.py

We have been focusing on C++ and ROS control lately. The Python bindings have not been a priority, unfortunately.

**Comment by BenBlumer** [comment]
Thanks for the reply. I'm looking forward to seeing the ROS control!
