### ISSUE TITLE
Zero calibration procedure is not feasible

### ISSUE THREAD

**Issue by mkoval** [BarrettTechnology/libbarrett#7]
We're trying to run the `bt-wam-zerocal` script on HERB. We ran into two issues:
1. the default home configuration is infeasible (set in `zerocal.conf`)
2. several of the configurations in the zerocal sequence are infeasible (set in `calibration.conf`)

We attempted to fix (1) by changing `zerocal.conf` to be:

```
home = ( 3.14, -1.96, 0.0, -0.86, 1.30, 0.00, 2.99 );
```

We attempted to fix (2) by changing the sequence of configurations in `calibration.conf` to:

```
wam7w:
(
    (1, ( 3.14, -1.57,   0.0,  1.57,   0.0,   0.0,   0.0 ), "the J1 scribe marks are aligned"),
    (3, ( 4.71, -1.57,   0.0,  1.57,   0.0,   0.0,   0.0 ), "the plastic elbow covers are vertical"),
    (2, ( 3.14,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0 ), "the inner link is vertical"),
    (4, ( 3.14,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0 ), "the J4 scribe marks are aligned"),
    (6, ( 3.14, -1.57,   0.0,  1.57,   0.0,   0.0,   0.0 ), "the tool-plate is horizontal"),
    (5, ( 3.14, -1.57,   0.0,   0.0,   0.0,   0.0,   0.0 ), "the J5 scribe marks are aligned"),
    (7, ( 3.14, -1.57,   0.0,  1.57,   0.0,   0.0,   0.0 ), "the J7 scribe marks are aligned")
);
```

With these changes, the `bt-wam-zerocal` script worked fine. However, the output `zerocal.conf` has the wrong home configuration:

```
home = ( 0.434197385, -1.96, 0.0, -0.86, 1.30, 0.00, 2.99 );
zeroangle = ( 3.572641255, 2.788777072, 1.412796306, 3.247437328, 0.1487961364, 6.09450567, 5.677262896 );
```

If we re-run the zero calibration, the arm (and especially J1) no longer go through the correct sequence of joint angles. We assume this is because the `home` configuration here does not reflect our changes. If I manually update this home configuration by adding our offsets, we _are_ able to successfully run the calibration again.

However, if we start `ex02_hold_position` in this state, the WAM violently accelerates and we have to immediately e-stop it. Our hypothesis is that this is caused by the bad zero calibration. In hindsight, we think it may also be caused by an incorrect gravity vector (see below).

There are two other aspects of our setup that might be causing problems:
1. our `j1` has modified joint limits (from 0.52 to 5.76 rad)
2. our WAM is mounted vertically, so the default gravity vector may be wrong

@bzenowich: Could you give us advice on how to proceed? Thanks!

Tagging @aaronjoh @cdellin @siddhss5.

**Comment by bzenowich** [comment]
Sorry for the delay, I'm not used to getting tech support questions on GitHub - normally we use our "support" email for this...

Before you run zerocal (in a radically different configuration), you need to set a reasonably accurate home position, and delete the zeroangle. E-Stop the WAM before running any cal progs to ensure the new data is loaded properly.

You will need to edit calibration.conf to contain useful zeroing positions (relative to your home position). You will also need to alter the gravitycal poses to tease out the most joint torque info from your system. See more info here:
http://web.barrett.com/support/WAM_Documentation/Dellin-Gravity-Compensation.pdf

You will also need to edit your world-to-base transform in /etc/barrett/wam7w.conf to match your system. This tells libbarrett how the gravity affects the links.

Finally, for dual-wam control, see here:
http://web.barrett.com/support/WAM_Documentation/DualWamControl.pdf
...and our demo here:
https://github.com/BarrettTechnology/libbarrett/blob/master/sandbox/two_wams.cpp

I hope this helps,

**Comment by mhariharasudan** [comment]
The Zero Calibration routine was supposed to perform only at Zero angles for all the Joints. The zerocal poses are to be modified if their home position is different. For any of the WAM which has modified Joint limits such that there is no 0 position in their range this routine fails.
A patch that would perform this zero calibration at all Joint position was included under the branch "zerocal".

@mkoval There was a small bug that was fixed today morning. Kindly refer to the latest commit.

**Comment by mkoval** [comment]
Thank you for fixing this! @aaronjoh and I were able to calibrate our WAM with the `zerocal` branch.

We've followed up by email with some related questions.
